# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Vanessa Phillips Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  This is Vanessa Phills website.
baseurl: "/" # the subpath of your site, e.g. /blog
permalink: /:title:output_ext
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: null
github_username: null
insta_username: v.phillips.art
facebook_username: null

copyright: '&copy; 2023<script>new Date().getFullYear()>2010&&document.write("-"+new Date().getFullYear());</script> Vanessa Phillips'

logo:
  mobile: "assets/images/logo/logomobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "assets/images/logo/logo.png"
  desktop_height: "83px"
  desktop_width: "364px"

plugins:
  - jekyll-environment-variables

sass:
  style: compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
  - TODO.md
